"""The three user mechanisms on one restaurant-booking scenario, with fake LLM/TTS clients.

- offline : ReplayUser — user turns at fixed timestamps (open loop).
- script  : UserSim + ScriptSource — fixed utterances, reactive timing, keyword barge-in, (fake) TTS audio.
- online  : UserSim + LLMSource — first turn given, later turns generated by an LLM,
            barge-in decided by an LLM (τ-Voice prompt), (fake) TTS audio.

The agent deliberately books "four people" in its second answer so that the user has
something to correct. No external service is called: FakeChat / FakeSpeech stand in
for a vLLM chat server and a TTS server.

    uv run python examples/user_modes.py --html runs/user_modes.html
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

import random
from array import array

from interaction_gym import AgentSpec, Background, Env, Segment, Task
from interaction_gym.audio import Audio
from interaction_gym.agents import CannedAgent
from interaction_gym.clients import Cached, FakeChat, FakeSpeech
from interaction_gym.media import MediaStore
from interaction_gym.traj import episode
from interaction_gym.user import (
    STOP,
    KeywordInterrupt,
    LLMInterrupt,
    LLMSource,
    ReplayUser,
    ScriptSource,
    UserSim,
    Voice,
)
from interaction_gym.viewer import export_html

AGENT_REPLIES = [
    "Sure, how many people will be joining, and what time works for you?",
    "Great, I have booked a table for four people at seven pm, and I will send a confirmation to your phone.",
    "Sorry about that, I have changed it to two people at seven pm.",
    "You're welcome, enjoy your dinner!",
]


def fake_user_llm(messages: list[dict]) -> str:
    """Mimics what a user LLM would say, from the last thing the agent said."""
    last = messages[-1]["content"].lower()
    if "how many" in last:
        return "Two people, around seven please."
    if "four" in last:
        return "No, no, just two people."
    if "changed it to two" in last:
        return f"Perfect, thank you! {STOP}"
    return "Okay."


def fake_interrupt_llm(messages: list[dict]) -> str:
    ongoing = [l for l in messages[-1]["content"].splitlines() if "[CURRENTLY SPEAKING, INCOMPLETE]" in l]
    return "YES" if ongoing and "four" in ongoing[-1].lower() else "NO"


TASK = Task(
    id="restaurant-booking",
    scenario={
        "persona": "You are Alex, a busy but friendly person calling a restaurant.",
        "instructions": "Book a table for two people tonight at around 7pm. Correct the agent if it gets a detail wrong.",
        "first_turn": "Hi, I'd like to book a table for tonight.",
        "replay_turns": [  # offline mode: pre-timed, including the non-directed sounds a user makes
            {"t": 0, "text": "Hi, I'd like to book a table for tonight."},
            {"t": 3600, "text": "", "kind": "noise", "dur": 400},
            {"t": 5500, "text": "Two people, around seven please."},
            {"t": 9000, "text": "mm-hmm", "kind": "backchannel"},
            {"t": 12000, "text": "No, no, just two people."},
            {"t": 15000, "text": "hold on, I'm on the phone", "kind": "aside"},
            {"t": 19500, "text": "Perfect, thank you!"},
        ],
        "turns": [  # script mode: fixed utterances, reactive timing
            {"t": 0, "text": "Hi, I'd like to book a table for tonight."},
            {"t": 5500, "text": "Two people, around seven please."},
            {"t": 12000, "text": "No, no, just two people."},
            {"t": 18000, "text": "Perfect, thank you!"},
        ],
    },
)


def make_user(mode: str):
    tts = Cached(FakeSpeech())
    if mode == "offline":
        return ReplayUser(TASK.scenario["replay_turns"], voice=Voice(tts))
    if mode == "script":
        return UserSim(ScriptSource(), Voice(tts), interrupt=KeywordInterrupt("four"))
    if mode == "online":
        return UserSim(LLMSource(FakeChat(fake_user_llm)), Voice(tts), interrupt=LLMInterrupt(FakeChat(fake_interrupt_llm)))
    raise ValueError(mode)


def cafe_ambience(seconds: int = 60, sr: int = 16000) -> Audio:
    """Synthetic low-level noise standing in for a recorded ambience track."""
    rng = random.Random(0)
    return Audio(array("h", (int(rng.gauss(0, 900)) for _ in range(seconds * sr))), sr)


async def run(mode: str, spec: AgentSpec = AgentSpec(), streaming: bool = False, min_words: int = 0) -> Env:
    background = []
    if mode == "online":  # a continuous microphone: user speech + ambience, every step
        spec = AgentSpec(spec.chunk_ms, spec.obs, spec.out, audio="user.audio")
        background = [Background(cafe_ambience(), gain_db=-12, offset_ms=5000)]
    env = Env({"user": make_user(mode)}, spec, max_ms=60_000, background=background)
    agent = CannedAgent(AGENT_REPLIES, spec, streaming=streaming, min_words=min_words)
    obs = await env.reset(TASK, seed=0)
    done = False
    while not done:
        obs, _, done = await env.step(agent.act(env.t, obs))
    return env


async def main(html: str | None) -> None:
    records = []
    cases = [("offline", False, 0), ("offline", False, 2), ("script", False, 0), ("online", False, 0), ("online", True, 0)]
    for mode, streaming, min_words in cases:
        env = await run(mode, streaming=streaming, min_words=min_words)
        name = mode + ("-streaming-agent" if streaming else "") + ("-listening-agent" if min_words else "")
        media = MediaStore(Path(html).parent if html else "runs")
        records.append(episode(env, f"{TASK.id}/{name}", media=media, meta={"agent_streaming": streaming, "agent_min_words": min_words}))
        if html is None:
            print(f"--- {name}")
            for f in env.log:
                d = f.data
                print(f"{f.t:6d}ms {f.stream:14s} " + (f"[{d.t0}-{d.end}] {d.transcript!r}" if isinstance(d, Segment) else repr(d)))
    if html:
        print(f"{len(records)} cases -> {export_html(records, html)}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--html")
    asyncio.run(main(ap.parse_args().html))
